# Generated by Django 4.2.3 on 2023-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=640),
        ),
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.TextField(max_length=640),
        ),
    ]
