# Generated by Django 4.2.3 on 2023-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_card_description_alter_token_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='phase',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
