# Generated by Django 4.2.3 on 2023-07-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_card_cp_card_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck', to='game.hero'),
        ),
        migrations.AlterField(
            model_name='card',
            name='phase',
            field=models.CharField(choices=[('main', 'main'), ('roll', 'roll'), ('instant', 'instant')], default='main', max_length=8),
        ),
        migrations.CreateModel(
            name='upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=640)),
                ('cost', models.IntegerField(default=1)),
                ('slot', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1)),
                ('level', models.IntegerField(choices=[(2, 2)], default=2)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades', to='game.hero')),
            ],
        ),
    ]
