# Generated by Django 4.2.3 on 2023-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_hero_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='name',
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='level',
            field=models.IntegerField(choices=[(2, 2), (3, 3)], default=2),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='slot',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
        ),
    ]
