# Generated by Django 4.2.3 on 2023-07-20 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_upgrade_name_alter_upgrade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
