# Generated by Django 4.2.3 on 2023-07-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_upgrade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='five',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='four',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='one',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='six',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='three',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='two',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
