# Generated by Django 4.2.3 on 2023-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_hero_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='tokens',
            field=models.ManyToManyField(blank=True, null=True, related_name='heroes', to='game.token'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='slot',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1),
        ),
    ]
