# Generated by Django 4.2.3 on 2023-07-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_hero_tokens_alter_upgrade_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='tokens',
            field=models.ManyToManyField(blank=True, related_name='heroes', to='game.token'),
        ),
    ]
