# Generated by Django 4.2.3 on 2023-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
